resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: asdfasdf

jobs:
- template: azure-pipelines.yml@MicrosoftIISCommon # Template reference