resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS

jobs:
- template: azure-pipelineses.yml@Microsoft/IIS.Common  # Template reference