resources:
  repositories:
    - repository: bariscaglar/testrepo
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS

jobs:
- template: azure-pipelines.yml@Microsoft/IIS.Common  # Template reference