name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - bangbingsyb/ci-pr-validation

pr:
  branches:
    include:
    - bangbingsyb/ci-pr-validation

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-PAT

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEng-MicroBuildV2CustomPool'
    agentPoolDemandTeam: 'IISAdmin'
    solution: '**\Compression.sln'
    productMajor: 1
    productMinor: 0
    signType: 'test'
    publishArtifactInstallers: 'true'